services:
  postgres_test_project:
    image: postgres:16.4-alpine3.20
    container_name: postgres_test_project
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "main"
    ports:
      - "127.0.0.1:44444:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis_test_project:
    image: redis:alpine
    container_name: redis_test_project
    restart: always
    ports:
      - "127.0.0.1:44445:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

